### ISSUE TITLE
ReferenceError: SCRIPT is not defined

### ISSUE THREAD

**Issue by drlogout** [anderly/dnsimple-cli#3]
If I run dnsimple I get the following error:

```bash
$ dnsimple
/usr/local/lib/node_modules/dnsimple-cli/node_modules/streamline/deps/narcissus/lib/jsparse.js:246
        return { type: SCRIPT,
                       ^

ReferenceError: SCRIPT is not defined
    at scriptInit (/usr/local/lib/node_modules/dnsimple-cli/node_modules/streamline/deps/narcissus/lib/jsparse.js:246:24)
    at Script (/usr/local/lib/node_modules/dnsimple-cli/node_modules/streamline/deps/narcissus/lib/jsparse.js:152:29)
    at parse (/usr/local/lib/node_modules/dnsimple-cli/node_modules/streamline/deps/narcissus/lib/jsparse.js:1431:17)
    at new Template (/usr/local/lib/node_modules/dnsimple-cli/node_modules/streamline/lib/callbacks/transform.js:198:15)
    at exports.undefined.window.Streamline (/usr/local/lib/node_modules/dnsimple-cli/node_modules/streamline/lib/callbacks/transform.js:357:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/dnsimple-cli/node_modules/streamline/lib/callbacks/transform.js:1468:3)
    at Module._compile (module.js:570:32)
    at Module.pModule._compile (/usr/local/lib/node_modules/dnsimple-cli/node_modules/streamline/lib/compiler/register.js:44:15)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

OS: macOS 10.12.4
Node version: v6.10.0 via Homebrew
Npm version: 4.1.2
dnsimple-cli@0.3.2
dnsimple@1.0.0

Cheers
Chris

**Comment by anderly** [comment]
I'll take a look. This project is a bit stale and due for a refresh, but I'm swamped at the moment and might not be able to get to it for awhile.

**Comment by davidjrice** [comment]
So, I'm getting this too; I tried both

* `npm install -g dnsimple-cli`
* `npm install -g anderly/dnsimple-cli`

### environment

* **OS:** macOS 10.13.4
* **node:** v9.11.1
* **npm:** 5.6.0

then uninstalled node/npm and updated to latest (via brew)

* **node:** v10.4.1
* **npm:** 6.1.0

any pointers to debug further? and I can have a look

**Comment by stevepaulo** [comment]
Just FYI, it's been nearly 3 years and this issue still exists.
